const mongoose = require("mongoose");
require("dotenv").config();

const Product = require("./models/Product");

const products = [
  {
    productId: 1,
    name: "Potato (Aloo)",
    category: "Fruits & Vegetables",
    categorySlug: "fruits-vegetables",
    price: 21,
    mrp: 24,
    discount: 12,
    quantity: "1 kg",
    description: "Fresh potatoes perfect for everyday cooking.",
    image: "https://placehold.co/600x600?text=Potato",
    stock: 20,
  },
  {
    productId: 2,
    name: "Onion (Pyaz)",
    category: "Fruits & Vegetables",
    categorySlug: "fruits-vegetables",
    price: 56,
    mrp: 67,
    discount: 16,
    quantity: "1 kg",
    description: "Fresh onions suitable for everyday cooking.",
    image: "https://placehold.co/600x600?text=Onion",
    stock: 20,
  },
  {
    productId: 3,
    name: "Green Chilli",
    category: "Fruits & Vegetables",
    categorySlug: "fruits-vegetables",
    price: 16,
    mrp: 19,
    discount: 15,
    quantity: "100 g",
    description: "Fresh green chillies with a spicy flavour.",
    image: "https://placehold.co/600x600?text=Green+Chilli",
    stock: 25,
  },
  {
    productId: 4,
    name: "Ginger (Adrak)",
    category: "Fruits & Vegetables",
    categorySlug: "fruits-vegetables",
    price: 52,
    mrp: 66,
    discount: 21,
    quantity: "200 g",
    description: "Fresh ginger for cooking and beverages.",
    image: "https://placehold.co/600x600?text=Ginger",
    stock: 15,
  },
  {
    productId: 5,
    name: "Desi Tomato (Tamatar)",
    category: "Fruits & Vegetables",
    categorySlug: "fruits-vegetables",
    price: 24,
    mrp: 29,
    discount: 17,
    quantity: "500 g",
    description: "Fresh juicy tomatoes for cooking and salads.",
    image: "https://placehold.co/600x600?text=Tomato",
    stock: 30,
  },

  {
    productId: 6,
    name: "Amul Taaza Milk",
    category: "Dairy & Breakfast",
    categorySlug: "dairy-breakfast",
    price: 30,
    mrp: 32,
    discount: 6,
    quantity: "500 ml",
    description: "Fresh and nutritious toned milk for everyday use.",
    image: "https://placehold.co/600x600?text=Amul+Milk",
    stock: 30,
  },
  {
    productId: 7,
    name: "Amul Butter",
    category: "Dairy & Breakfast",
    categorySlug: "dairy-breakfast",
    price: 56,
    mrp: 60,
    discount: 7,
    quantity: "100 g",
    description: "Smooth and creamy butter perfect for breakfast and cooking.",
    image: "https://placehold.co/600x600?text=Amul+Butter",
    stock: 25,
  },
  {
    productId: 8,
    name: "Amul Cheese Slices",
    category: "Dairy & Breakfast",
    categorySlug: "dairy-breakfast",
    price: 95,
    mrp: 110,
    discount: 14,
    quantity: "200 g",
    description: "Creamy cheese slices perfect for sandwiches and snacks.",
    image: "https://placehold.co/600x600?text=Cheese+Slices",
    stock: 20,
  },
  {
    productId: 9,
    name: "Brown Bread",
    category: "Dairy & Breakfast",
    categorySlug: "dairy-breakfast",
    price: 45,
    mrp: 50,
    discount: 10,
    quantity: "400 g",
    description: "Soft and fresh brown bread for a wholesome breakfast.",
    image: "https://placehold.co/600x600?text=Brown+Bread",
    stock: 20,
  },
  {
    productId: 10,
    name: "Farm Fresh Eggs",
    category: "Dairy & Breakfast",
    categorySlug: "dairy-breakfast",
    price: 72,
    mrp: 80,
    discount: 10,
    quantity: "6 pcs",
    description: "Fresh eggs suitable for breakfast and everyday cooking.",
    image: "https://placehold.co/600x600?text=Fresh+Eggs",
    stock: 30,
  },

  {
    productId: 11,
    name: "Lay's Classic Salted Chips",
    category: "Snacks",
    categorySlug: "snacks",
    price: 20,
    mrp: 20,
    discount: 0,
    quantity: "50 g",
    description: "Crispy and delicious classic salted potato chips.",
    image: "https://placehold.co/600x600?text=Lays+Chips",
    stock: 30,
  },
  {
    productId: 12,
    name: "Kurkure Masala Munch",
    category: "Snacks",
    categorySlug: "snacks",
    price: 20,
    mrp: 20,
    discount: 0,
    quantity: "90 g",
    description: "Crunchy and spicy masala flavoured snack.",
    image: "https://placehold.co/600x600?text=Kurkure",
    stock: 30,
  },
  {
    productId: 13,
    name: "Haldiram's Aloo Bhujia",
    category: "Snacks",
    categorySlug: "snacks",
    price: 65,
    mrp: 70,
    discount: 7,
    quantity: "200 g",
    description: "Crispy and flavourful traditional Indian namkeen.",
    image: "https://placehold.co/600x600?text=Aloo+Bhujia",
    stock: 25,
  },
  {
    productId: 14,
    name: "Parle-G Biscuits",
    category: "Snacks",
    categorySlug: "snacks",
    price: 30,
    mrp: 35,
    discount: 14,
    quantity: "250 g",
    description: "Classic crunchy glucose biscuits perfect with tea.",
    image: "https://placehold.co/600x600?text=Parle-G",
    stock: 35,
  },
  {
    productId: 15,
    name: "Bingo Tedhe Medhe",
    category: "Snacks",
    categorySlug: "snacks",
    price: 20,
    mrp: 20,
    discount: 0,
    quantity: "70 g",
    description: "Crunchy twisted snacks with a delicious masala flavour.",
    image: "https://placehold.co/600x600?text=Bingo",
    stock: 25,
  },

  {
    productId: 16,
    name: "Coca-Cola",
    category: "Beverages",
    categorySlug: "beverages",
    price: 40,
    mrp: 40,
    discount: 0,
    quantity: "750 ml",
    description: "Refreshing chilled carbonated soft drink.",
    image: "https://placehold.co/600x600?text=Coca-Cola",
    stock: 30,
  },
  {
    productId: 17,
    name: "Real Fruit Juice",
    category: "Beverages",
    categorySlug: "beverages",
    price: 110,
    mrp: 120,
    discount: 8,
    quantity: "1 L",
    description: "Refreshing fruit juice for a delicious everyday drink.",
    image: "https://placehold.co/600x600?text=Fruit+Juice",
    stock: 20,
  },
  {
    productId: 18,
    name: "Tata Tea Gold",
    category: "Beverages",
    categorySlug: "beverages",
    price: 145,
    mrp: 160,
    discount: 9,
    quantity: "250 g",
    description: "Aromatic tea leaves for a refreshing cup of tea.",
    image: "https://placehold.co/600x600?text=Tata+Tea",
    stock: 25,
  },
  {
    productId: 19,
    name: "Nescafe Classic Coffee",
    category: "Beverages",
    categorySlug: "beverages",
    price: 175,
    mrp: 190,
    discount: 8,
    quantity: "50 g",
    description: "Rich and aromatic instant coffee for your daily cup.",
    image: "https://placehold.co/600x600?text=Nescafe",
    stock: 20,
  },
  {
    productId: 20,
    name: "Bisleri Mineral Water",
    category: "Beverages",
    categorySlug: "beverages",
    price: 20,
    mrp: 20,
    discount: 0,
    quantity: "1 L",
    description: "Packaged drinking water for everyday hydration.",
    image: "https://placehold.co/600x600?text=Bisleri",
    stock: 40,
  },

  {
    productId: 21,
    name: "White Bread",
    category: "Bakery",
    categorySlug: "bakery",
    price: 35,
    mrp: 40,
    discount: 13,
    quantity: "400 g",
    description:
      "Soft and fresh white bread, perfect for sandwiches and breakfast.",
    image: "https://placehold.co/600x600?text=White+Bread",
    stock: 25,
  },
  {
    productId: 22,
    name: "Chocolate Cake",
    category: "Bakery",
    categorySlug: "bakery",
    price: 199,
    mrp: 220,
    discount: 10,
    quantity: "500 g",
    description: "Soft and delicious chocolate cake for every occasion.",
    image: "https://placehold.co/600x600?text=Chocolate+Cake",
    stock: 10,
  },
  {
    productId: 23,
    name: "Croissant",
    category: "Bakery",
    categorySlug: "bakery",
    price: 75,
    mrp: 85,
    discount: 12,
    quantity: "2 pcs",
    description: "Fresh and flaky buttery croissants, perfect for breakfast.",
    image: "https://placehold.co/600x600?text=Croissant",
    stock: 15,
  },
  {
    productId: 24,
    name: "Pav Bread",
    category: "Bakery",
    categorySlug: "bakery",
    price: 30,
    mrp: 35,
    discount: 14,
    quantity: "6 pcs",
    description: "Soft and fresh pav bread, perfect for snacks and meals.",
    image: "https://placehold.co/600x600?text=Pav+Bread",
    stock: 25,
  },
  {
    productId: 25,
    name: "Chocolate Muffin",
    category: "Bakery",
    categorySlug: "bakery",
    price: 90,
    mrp: 100,
    discount: 10,
    quantity: "2 pcs",
    description: "Soft chocolate muffins with a rich chocolate flavour.",
    image: "https://placehold.co/600x600?text=Chocolate+Muffin",
    stock: 15,
  },

  {
    productId: 26,
    name: "Vim Dishwash Liquid",
    category: "Household",
    categorySlug: "household",
    price: 125,
    mrp: 140,
    discount: 11,
    quantity: "500 ml",
    description: "Effective dishwashing liquid for removing grease and stains.",
    image: "https://placehold.co/600x600?text=Vim+Dishwash",
    stock: 20,
  },
  {
    productId: 27,
    name: "Surf Excel Matic",
    category: "Household",
    categorySlug: "household",
    price: 235,
    mrp: 260,
    discount: 10,
    quantity: "1 kg",
    description: "Powerful detergent powder for a clean and fresh wash.",
    image: "https://placehold.co/600x600?text=Surf+Excel",
    stock: 20,
  },
  {
    productId: 28,
    name: "Harpic Bathroom Cleaner",
    category: "Household",
    categorySlug: "household",
    price: 95,
    mrp: 110,
    discount: 14,
    quantity: "500 ml",
    description: "Bathroom cleaner that helps remove tough stains and dirt.",
    image: "https://placehold.co/600x600?text=Harpic",
    stock: 20,
  },
  {
    productId: 29,
    name: "Colin Glass Cleaner",
    category: "Household",
    categorySlug: "household",
    price: 105,
    mrp: 120,
    discount: 13,
    quantity: "500 ml",
    description: "Glass cleaner for sparkling clean windows and surfaces.",
    image: "https://placehold.co/600x600?text=Colin",
    stock: 20,
  },
  {
    productId: 30,
    name: "Scotch-Brite Scrub Pad",
    category: "Household",
    categorySlug: "household",
    price: 45,
    mrp: 50,
    discount: 10,
    quantity: "3 pcs",
    description: "Durable scrub pads for cleaning dishes and kitchen surfaces.",
    image: "https://placehold.co/600x600?text=Scrub+Pad",
    stock: 25,
  },

  // ==========================================
  // PHARMACY
  // ==========================================

  {
    productId: 31,
    name: "Dolo 650",
    category: "Pharmacy",
    categorySlug: "pharmacy",
    price: 32,
    mrp: 35,
    discount: 9,
    quantity: "15 tablets",
    description: "Paracetamol tablets for fever and mild pain relief.",
    image: "https://placehold.co/600x600?text=Dolo+650",
    stock: 30,
  },

  {
    productId: 32,
    name: "Crocin Advance",
    category: "Pharmacy",
    categorySlug: "pharmacy",
    price: 28,
    mrp: 32,
    discount: 13,
    quantity: "15 tablets",
    description: "Paracetamol tablets commonly used for fever and body pain.",
    image: "https://placehold.co/600x600?text=Crocin",
    stock: 30,
  },

  {
    productId: 33,
    name: "Dettol Antiseptic Liquid",
    category: "Pharmacy",
    categorySlug: "pharmacy",
    price: 85,
    mrp: 95,
    discount: 11,
    quantity: "250 ml",
    description:
      "Antiseptic liquid for everyday personal and household hygiene.",
    image: "https://placehold.co/600x600?text=Dettol",
    stock: 25,
  },

  {
    productId: 34,
    name: "Savlon Handwash",
    category: "Pharmacy",
    categorySlug: "pharmacy",
    price: 99,
    mrp: 110,
    discount: 10,
    quantity: "250 ml",
    description: "Gentle handwash for everyday hand hygiene.",
    image: "https://placehold.co/600x600?text=Savlon",
    stock: 25,
  },

  {
    productId: 35,
    name: "Band-Aid Flexible Strips",
    category: "Pharmacy",
    categorySlug: "pharmacy",
    price: 45,
    mrp: 50,
    discount: 10,
    quantity: "10 strips",
    description: "Flexible adhesive strips for covering minor cuts and wounds.",
    image: "https://placehold.co/600x600?text=Band-Aid",
    stock: 30,
  },

  // ==========================================
  // PET SUPPLIES
  // ==========================================

  {
    productId: 36,
    name: "Pedigree Adult Dog Food",
    category: "Pet Supplies",
    categorySlug: "pet-supplies",
    price: 425,
    mrp: 460,
    discount: 8,
    quantity: "1 kg",
    description: "Complete and balanced food for adult dogs.",
    image: "https://placehold.co/600x600?text=Pedigree",
    stock: 20,
  },

  {
    productId: 37,
    name: "Whiskas Adult Cat Food",
    category: "Pet Supplies",
    categorySlug: "pet-supplies",
    price: 210,
    mrp: 230,
    discount: 9,
    quantity: "480 g",
    description: "Tasty and nutritious food specially made for adult cats.",
    image: "https://placehold.co/600x600?text=Whiskas",
    stock: 20,
  },

  {
    productId: 38,
    name: "Drools Puppy Food",
    category: "Pet Supplies",
    categorySlug: "pet-supplies",
    price: 350,
    mrp: 390,
    discount: 10,
    quantity: "1 kg",
    description: "Nutritious puppy food for healthy growth and development.",
    image: "https://placehold.co/600x600?text=Drools",
    stock: 20,
  },

  {
    productId: 39,
    name: "Pedigree Dog Treats",
    category: "Pet Supplies",
    categorySlug: "pet-supplies",
    price: 125,
    mrp: 140,
    discount: 11,
    quantity: "200 g",
    description: "Tasty dog treats suitable for training and rewarding pets.",
    image: "https://placehold.co/600x600?text=Dog+Treats",
    stock: 25,
  },

  {
    productId: 40,
    name: "Cat Litter",
    category: "Pet Supplies",
    categorySlug: "pet-supplies",
    price: 299,
    mrp: 330,
    discount: 9,
    quantity: "5 kg",
    description: "Absorbent cat litter for keeping your pet's area clean.",
    image: "https://placehold.co/600x600?text=Cat+Litter",
    stock: 15,
  },

  // ==========================================
  // BABY CARE
  // ==========================================

  {
    productId: 41,
    name: "Pampers Baby Diapers",
    category: "Baby Care",
    categorySlug: "baby-care",
    price: 399,
    mrp: 450,
    discount: 11,
    quantity: "20 pcs",
    description: "Soft and comfortable diapers designed for babies.",
    image: "https://placehold.co/600x600?text=Pampers",
    stock: 20,
  },

  {
    productId: 42,
    name: "Himalaya Baby Lotion",
    category: "Baby Care",
    categorySlug: "baby-care",
    price: 145,
    mrp: 165,
    discount: 12,
    quantity: "200 ml",
    description: "Gentle moisturizing lotion for baby's delicate skin.",
    image: "https://placehold.co/600x600?text=Baby+Lotion",
    stock: 20,
  },

  {
    productId: 43,
    name: "Johnson's Baby Shampoo",
    category: "Baby Care",
    categorySlug: "baby-care",
    price: 175,
    mrp: 195,
    discount: 10,
    quantity: "200 ml",
    description: "Mild shampoo specially formulated for baby's delicate hair.",
    image: "https://placehold.co/600x600?text=Baby+Shampoo",
    stock: 20,
  },

  {
    productId: 44,
    name: "Mamaearth Baby Cream",
    category: "Baby Care",
    categorySlug: "baby-care",
    price: 199,
    mrp: 225,
    discount: 12,
    quantity: "100 g",
    description: "Gentle moisturizing cream for baby's soft skin.",
    image: "https://placehold.co/600x600?text=Baby+Cream",
    stock: 20,
  },

  {
    productId: 45,
    name: "Baby Wipes",
    category: "Baby Care",
    categorySlug: "baby-care",
    price: 129,
    mrp: 150,
    discount: 14,
    quantity: "72 wipes",
    description: "Soft and gentle wipes for convenient baby care.",
    image: "https://placehold.co/600x600?text=Baby+Wipes",
    stock: 25,
  },
];

async function seedProducts() {
  try {
    await mongoose.connect(process.env.MONGODB_URI);

    console.log("MongoDB connected");

    await Product.deleteMany({});

    await Product.insertMany(products);

    console.log(`${products.length} products inserted successfully`);

    await mongoose.disconnect();

    console.log("MongoDB disconnected");
  } catch (error) {
    console.error("Product seeding failed:", error.message);

    process.exit(1);
  }
}

seedProducts();
